[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Team Rituals

## Ritual 1:<br/>Non\-work related team routines<br/>\(every two weeks\)

### Why

#### To contribute to team cohesion,<br/>engagement, and motivation

#### To help drive individual well\-beeing<br/>and raise a sense of belonging

### How

#### Be proactive about taking time to connect

#### Give importance to non\-work\-related routines

#### Preferrably in person, but video is OK

### Examples

#### Coffee break

#### Lunch break

#### Shared games \(?\)

## Ritual 2:<br/>Two\-way feedback loops<br/>\(every six weeks\)
> leftSide=`true`


### Why

#### Clarify expectations

#### Improve performance

#### Increase reflection

#### Increase self\-awarenerss

#### Build trust through openness

### How

#### Be constructive

#### Represent feedback as an opportunity<br/>for development

#### Base feedback on observations<br/>and specific examples

### Examples

#### Regular 1:1

#### Achieved goals celebration

#### Illustrative feedback

## Ritual 3:<br/>Gathering in work anchor points<br/>\(monthly\)
> leftSide=`true`


### Why

#### Encourage social interaction

#### Increase opportunity of<br/>spontaneous meetings

#### Help improve bonding and<br/>belonging

### How

#### Make work anchor points a<br/>place of encounter

#### Organize visits

### Examples

#### In\-person brainstork session

#### Encourage spontaneous<br/>coffee date

#### Monthly lunch and learn

## Ritual 4:<br/>Moments to connect and disconnect<br/>\(each time a member joins, a reminder every semester\)

### Why

#### Create work\-life balance

#### Improve time management

#### Encourage autonomy and freedom<br/>on how to work

#### Strengthen well\-being

### How

#### Define expectations for team<br/>availability

#### Establish rules on the moments to<br/>Connect and Disconnect

#### Share team members availability with<br/>the team

#### Encourage team members to find moments<br/>to disconnect

#### Put focus on results instead time spent<br/>on tasks

### Examples

#### Organize team discussion on personal<br/>preference for work times\. Make sure<br/>it aligns with required availability

#### Chat on what stops team member from<br/>taking time off

#### Book a daily walk, or lunch, or<br/>other routines

## Ritual 5:<br/>Individual touch points for personal discussion<br/>\(every six weeks\)
> leftSide=`true`


### Why

#### Improve relationships

#### Cultivate trust

#### Contribute to employee well\-being,<br/>motivation, and performance

#### Understand team's well\-being drivers

### How

#### Set up individual touch points

#### Focus on day\-to\-day needs, general situations,<br/>overall mood, experiences

#### Create a solution\-oriented<br/>atmosphere

### Examples

#### Short 1:1 related to concerns<br/>and struggles

#### Extended 1:1 to discuss situation,<br/>and focus on removing difficulties

## Ritual 6:<br/>Development touchpoints for career ambition<br/>\(quarterly\)

### Why

#### Encourage reflection on expectations<br/>and opportunities

#### Help accelerate development

#### Enhance engagement and retention

#### Challenge status quo and push people<br/>out of cmfort zone

### How

#### Informal setting for open and trustful atmosphere

#### Identify concrete actions to reach their goals

#### Focus on \`so what?\`\-question

### Example

#### Organize a meeting on what's long\-term vision<br/>of an employee, what's important for them

#### Orginize coaching sessions

## Ritual 7:<br/>Regular information sessions<br/>\(quarterly\)
> leftSide=`true`


### Why

#### Foster greater transparency

#### Enable creativity and innovation

#### Help strengthen commitment to the organization,<br/>motivate employees through recognition

### How

#### Information sessions

##### Achievements

##### Insights

##### Lessons learned

##### Other relevant knowledge<br/>applicable for the team

#### Record relevant information

### Examples

#### Organize all\-hands meeting\(s\)<br/>to showcase work

#### Organize deep\-dive session<br/>with subject matter experts

## Organize

### Step 1: analyze existing<br/>practices

#### What are they?

#### When are we doing them?

#### Why are we doing them?

#### Who are they benefiting?

#### How are they similar to<br/>The Team Rituals?

### Step 2: design team rituals

#### What could the seven Team Rituals<br/>look like for your team?

#### Can you reuse existing routines?

#### How can you make sure rituals benefit?

#### How can you involve your team in the process?

### Step 3: learn and adopt

#### What's working well?

#### How can we change to create more value?
